LOCAL_PATH := $(call my-dir)
LIBCAIRO_SRC = \
	       src/cairo-analysis-surface.c            \
	       src/cairo-arc.c                         \
	       src/cairo-array.c                       \
	       src/cairo-atomic.c                      \
	       src/cairo-base64-stream.c               \
	       src/cairo-base85-stream.c               \
	       src/cairo-bentley-ottmann-rectangular.c \
	       src/cairo-bentley-ottmann-rectilinear.c \
	       src/cairo-bentley-ottmann.c             \
	       src/cairo-botor-scan-converter.c        \
	       src/cairo-boxes-intersect.c             \
	       src/cairo-boxes.c                       \
	       src/cairo.c                             \
	       src/cairo-cache.c                       \
	       src/cairo-cff-subset.c                  \
	       src/cairo-clip-boxes.c                  \
	       src/cairo-clip-polygon.c                \
	       src/cairo-clip-region.c                 \
	       src/cairo-clip-surface.c                \
	       src/cairo-clip-tor-scan-converter.c     \
	       src/cairo-clip.c                        \
	       src/cairo-color.c                       \
	       src/cairo-composite-rectangles.c        \
	       src/cairo-compositor.c                  \
	       src/cairo-contour.c                     \
	       src/cairo-damage.c                      \
	       src/cairo-debug.c                       \
	       src/cairo-default-context.c             \
	       src/cairo-deflate-stream.c              \
	       src/cairo-device.c                      \
	       src/cairo-error.c                       \
	       src/cairo-fallback-compositor.c         \
	       src/cairo-fixed.c                       \
	       src/cairo-font-face-twin-data.c         \
	       src/cairo-font-face-twin.c              \
	       src/cairo-font-face.c                   \
	       src/cairo-font-options.c                \
	       src/cairo-freed-pool.c                  \
	       src/cairo-freelist.c                    \
	       src/cairo-gstate.c                      \
	       src/cairo-hash.c                        \
	       src/cairo-hull.c                        \
	       src/cairo-image-compositor.c            \
	       src/cairo-image-info.c                  \
	       src/cairo-image-source.c                \
	       src/cairo-image-surface.c               \
	       src/cairo-lzw.c                         \
	       src/cairo-mask-compositor.c             \
	       src/cairo-matrix.c                      \
	       src/cairo-mesh-pattern-rasterizer.c     \
	       src/cairo-misc.c                        \
	       src/cairo-mono-scan-converter.c         \
	       src/cairo-mutex.c                       \
	       src/cairo-no-compositor.c               \
	       src/cairo-observer.c                    \
	       src/cairo-output-stream.c               \
	       src/cairo-paginated-surface.c           \
	       src/cairo-path-bounds.c                 \
	       src/cairo-path-fill.c                   \
	       src/cairo-path-fixed.c                  \
	       src/cairo-path-in-fill.c                \
	       src/cairo-path-stroke-boxes.c           \
	       src/cairo-path-stroke-polygon.c         \
	       src/cairo-path-stroke-tristrip.c        \
	       src/cairo-path-stroke.c                 \
	       src/cairo-path.c                        \
	       src/cairo-pattern.c                     \
	       src/cairo-pen.c                         \
	       src/cairo-polygon-intersect.c           \
	       src/cairo-polygon-reduce.c              \
	       src/cairo-polygon.c                     \
	       src/cairo-raster-source-pattern.c       \
	       src/cairo-recording-surface.c           \
	       src/cairo-rectangle.c                   \
	       src/cairo-rectangular-scan-converter.c  \
	       src/cairo-region.c                      \
	       src/cairo-rtree.c                       \
	       src/cairo-scaled-font-subsets.c         \
	       src/cairo-scaled-font.c                 \
	       src/cairo-shape-mask-compositor.c       \
	       src/cairo-slope.c                       \
	       src/cairo-spans-compositor.c            \
	       src/cairo-spans.c                       \
	       src/cairo-spline.c                      \
	       src/cairo-stroke-dash.c                 \
	       src/cairo-stroke-style.c                \
	       src/cairo-surface-clipper.c             \
	       src/cairo-surface-fallback.c            \
	       src/cairo-surface-observer.c            \
	       src/cairo-surface-offset.c              \
	       src/cairo-surface-snapshot.c            \
	       src/cairo-surface-subsurface.c          \
	       src/cairo-surface-wrapper.c             \
	       src/cairo-surface.c                     \
	       src/cairo-tee-surface.c                 \
	       src/cairo-time.c                        \
	       src/cairo-tor-scan-converter.c          \
	       src/cairo-tor22-scan-converter.c        \
	       src/cairo-toy-font-face.c               \
	       src/cairo-traps-compositor.c            \
	       src/cairo-traps.c                       \
	       src/cairo-tristrip.c                    \
	       src/cairo-truetype-subset.c             \
	       src/cairo-type1-fallback.c              \
	       src/cairo-type1-glyph-names.c           \
	       src/cairo-type1-subset.c                \
	       src/cairo-type3-glyph-surface.c         \
	       src/cairo-unicode.c                     \
	       src/cairo-user-font.c                   \
	       src/cairo-version.c                     \
	       src/cairo-wideint.c                     \

LIBCAIRO_CFLAGS:=                                                     \
    -DPACKAGE_VERSION="\"scheme-cairo\""                              \
    -DPACKAGE_BUGREPORT="\"http://github.com/alvatarc/scheme-cairo\"" \
    -DCAIRO_NO_MUTEX=1                                                \
    -DHAVE_STDINT_H                                                   \
    -DHAVE_UINT64_T                                                   \


include $(CLEAR_VARS)

LOCAL_MODULE    := libcairo
LOCAL_CFLAGS    := -O2 $(LIBCAIRO_CFLAGS) -Ipixman/pixman -Ipixman-extra -Isrc -Icairo-extra -Wno-missing-field-initializers -Wno-attributes  -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -w
LOCAL_LDFLAGS   := -lz
LOCAL_SRC_FILES := $(LIBCAIRO_SRC)

include $(BUILD_STATIC_LIBRARY)
