#!/usr/bin/env sh

platform_type="$1"

ios_platform="$platform_type.platform"

developer_dir="`xcode-select --print-path`"
platforms_dir="$developer_dir/Platforms"
ios_platform_dir="$platforms_dir/$ios_platform"
ios_sdks="$ios_platform_dir/Developer/SDKs"

sdk_version=`(cd "$ios_sdks" && ls -1d *.sdk |sed -e 's/\.sdk$//' -e 's/^[^0-9\.]*//' | awk 'BEGIN{best = 0.0}($0 + 0.0) > best + 0.0{best = $0;}END{print best}')`

if (( $? ))
then
  echo "Error finding SDK path" >&2
  exit 1
fi

ios_sdk="$platform_type$sdk_version.sdk"

ios_sdk_dir="$ios_sdks/$ios_sdk"

echo $ios_sdk_dir
